/**
 * Generated / vendored source detection for `findDuplicates`. Protobuf output, OpenAPI clients,
 * `*.generated.*` files, and Jest/Vitest `__snapshots__/*.snap` files are genuinely repetitive by
 * construction — every message type (or serialized snapshot) looks like every other one — but
 * that repetition isn't a copy-paste problem a human would act on, and by sheer line count it
 * swamps real findings. `findDuplicates` drops these by default (override with
 * `includeGenerated: true`).
 *
 * Detection is intentionally coarse — a path heuristic plus a first-bytes marker scan, the same
 * risk tolerance the rest of this module's noise gates take. No glob dependency: the configurable
 * `ignoreGlobs` supports the same two shapes the built-in list uses (`**​/segment/**` and
 * `*.suffix`), not full glob syntax.
 */
import path from "node:path";

/** Path segments that, when they appear anywhere in a file's path, mark it generated. */
const GENERATED_PATH_SEGMENTS: ReadonlySet<string> = new Set([
  "generated",
  "__generated__",
  "__generated",
  "gen",
  // Jest / Vitest snapshot directories — auto-written by the test runner, and their uniform
  // structure self-matches ~20x under a sliding window (reported dogfooding box-ui-elements).
  "__snapshots__",
]);

/** Basename suffixes that mark a file as tool-generated (protobuf, codegen, snapshots, etc.). */
const GENERATED_BASENAME_SUFFIXES: readonly string[] = [
  ".pb.go",
  ".pb.ts",
  ".pb.js",
  "_pb2.py",
  "_pb2.pyi",
  "_pb.dart",
  ".g.dart",
  ".generated.ts",
  ".generated.tsx",
  ".generated.js",
  ".generated.jsx",
  "_generated.go",
  ".gen.go",
  ".gen.ts",
  ".snap",
];

/** Case-insensitive markers scanned for in the first {@link MARKER_SCAN_BYTES} of a file. */
const GENERATED_CONTENT_MARKERS: readonly string[] = [
  "@generated",
  "do not edit",
  "code generated by",
  "autogenerated",
  "auto-generated",
  "this file was automatically generated",
  "this is a generated file",
  "jest snapshot v1",
];

const MARKER_SCAN_BYTES = 500;

/**
 * @description Matches `relPath` against one of the simple `ignoreGlobs` shapes:
 *   `**​/name/**` (any path segment equals `name`) or `*.suffix` (basename ends with `.suffix`).
 *   Anything else is compared as a literal path-segment match. Not a full glob implementation.
 * @param relPath - Project-relative file path (POSIX or platform separators).
 * @param glob - One configured pattern.
 * @returns Whether `relPath` matches `glob`.
 */
function matchesSimpleGlob(relPath: string, glob: string): boolean {
  const segments = relPath.split(/[\\/]/);
  const segmentGlob = /^\*\*\/(.+?)\/\*\*$/.exec(glob);
  if (segmentGlob) return segments.includes(segmentGlob[1] as string);
  if (glob.startsWith("*.")) return path.basename(relPath).endsWith(glob.slice(1));
  return segments.includes(glob);
}

/**
 * @description Whether a file's path alone marks it as generated — a known codegen basename
 *   suffix, a generated-output directory segment, or a caller-supplied `ignoreGlobs` match.
 *   Cheap and synchronous, so it runs before the file is read.
 * @param relPath - Project-relative file path.
 * @param ignoreGlobs - Extra patterns from `MokoshConfig.duplication.ignoreGlobs`.
 * @returns Whether `relPath` should be treated as generated.
 */
export function isGeneratedPath(relPath: string, ignoreGlobs: readonly string[] = []): boolean {
  const segments = relPath.split(/[\\/]/);
  if (segments.some((segment) => GENERATED_PATH_SEGMENTS.has(segment))) return true;
  const base = path.basename(relPath);
  if (GENERATED_BASENAME_SUFFIXES.some((suffix) => base.endsWith(suffix))) return true;
  return ignoreGlobs.some((glob) => matchesSimpleGlob(relPath, glob));
}

/**
 * @description Whether the start of a file's source carries a generated-by marker
 *   (`@generated`, `DO NOT EDIT`, `Code generated by …`, etc.). Only the first
 *   {@link MARKER_SCAN_BYTES} characters are checked — codegen tools put the banner at the top.
 * @param source - Full file source.
 * @returns Whether a generated marker is present near the top of `source`.
 */
export function hasGeneratedMarker(source: string): boolean {
  const head = source.slice(0, MARKER_SCAN_BYTES).toLowerCase();
  return GENERATED_CONTENT_MARKERS.some((marker) => head.includes(marker));
}
