import { describe, expect, test } from "vitest";
import { hasGeneratedMarker, isGeneratedPath } from "./generated";

describe("isGeneratedPath", () => {
  test("flags codegen basename suffixes", () => {
    for (const p of [
      "api/service.pb.go",
      "gen/user_pb2.py",
      "src/models.generated.ts",
      "lib/client_generated.go",
      "a/b/schema.gen.ts",
    ]) {
      expect(isGeneratedPath(p)).toBe(true);
    }
  });

  test("flags generated-output directory segments", () => {
    expect(isGeneratedPath("src/generated/api.ts")).toBe(true);
    expect(isGeneratedPath("packages/core/__generated__/types.ts")).toBe(true);
  });

  test("flags test-runner snapshot files", () => {
    expect(isGeneratedPath("src/components/__snapshots__/Button.test.js.snap")).toBe(true);
    expect(isGeneratedPath("test/Foo.spec.tsx.snap")).toBe(true);
  });

  test("leaves ordinary source files alone", () => {
    expect(isGeneratedPath("src/graph/builder.ts")).toBe(false);
    expect(isGeneratedPath("src/generator.ts")).toBe(false);
  });

  test("honours extra ignoreGlobs in both supported shapes", () => {
    expect(isGeneratedPath("third_party/vendored/x.ts", ["**/vendored/**"])).toBe(true);
    expect(isGeneratedPath("src/openapi.client.ts", ["*.client.ts"])).toBe(true);
    expect(isGeneratedPath("src/keep.ts", ["**/vendored/**", "*.client.ts"])).toBe(false);
  });
});

describe("hasGeneratedMarker", () => {
  test("matches common banners near the top of a file", () => {
    expect(hasGeneratedMarker("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x")).toBe(
      true,
    );
    expect(hasGeneratedMarker("/* @generated */\nexport const x = 1;")).toBe(true);
    expect(hasGeneratedMarker("# AUTO-GENERATED FILE\nimport os")).toBe(true);
    expect(
      hasGeneratedMarker("// Jest Snapshot v1, https://goo.gl/fbAQLP\n\nexports[`x`] = `y`;"),
    ).toBe(true);
  });

  test("ignores a marker that only appears deep in the file", () => {
    const source = `${"x\n".repeat(400)}// do not edit\n`;
    expect(hasGeneratedMarker(source)).toBe(false);
  });

  test("does not match ordinary prose", () => {
    expect(hasGeneratedMarker("// This module generates a report from the graph.")).toBe(false);
  });
});
